version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4
      - image: circleci/mysql:5.7

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: composer install

      - run:
          name: Run tests
          command: ./vendor/bin/phpunit

  deploy:
    docker:
      - image: docker:stable

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build and push Docker images
          command: |
            docker build -t service1 service1/.
            docker build -t service2 service2/.
            docker build -t service3 service3/.
            docker tag service1 mydockerhub/service1
            docker tag service2 mydockerhub/service2
            docker tag service3 mydockerhub/service3
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push mydockerhub/service1
            docker push mydockerhub/service2
            docker push mydockerhub/service3

  deploy_to_clever_cloud:
    docker:
      - image: docker:stable

    steps:
      - checkout

      - run:
          name: Deploy to Clever Cloud
          command: |
            curl -X POST -H "Authorization: Bearer $CLEVER_CLOUD_TOKEN" -F "payload=@docker-compose.yml" https://api.clever-cloud.com/v2/apps/your-app-id/deploy
