version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: composer install

      - run:
          name: Run tests
          command: ./vendor/bin/phpunit
